#!/bin/sh
# $Id: INSTALL,v 1.6 2012/02/17 15:52:40 drmiller Exp $

export INSTALLPATH=${HOME}/tele-sb-sim

# path might have blanks!!!
pgm="${0}"
if [[ -L "${pgm}" ]]; then
	pgm=$(readlink "${pgm}")
fi
cwd="${pgm%/*}"
if [[ ! "${cwd}" -ef "${INSTALLPATH}" ]]; then
	echo "Moving ${cwd}..."
	rm -rf "${INSTALLPATH}"
	cp -r "${cwd}" "${INSTALLPATH}"
	exec "${INSTALLPATH}/${0##*/}"
	exit 1
fi
cd "${INSTALLPATH}"

e=0
for title in Switchboard Telephone; do
	if [[ ( -d ~/.gnome || -d ~/.gnome2 ) && -d ~/Desktop ]]; then
		echo "installing GNOME desktop ${title} shortcut..."
		cat ${title}.desktop.tmplt | while read line; do
			eval "echo \"${line}\""
		done >~/Desktop/${title}.desktop
		if [[ $? -ne 0 ]]; then ((e+=1)); fi
	elif [[ -f ~/.CFUserTextEncoding && -d ~/Desktop ]]; then
		echo "installing OSX desktop ${title} shortcut..."
		rm -rf ~/Desktop/${title}.app
		mkdir -p ~/Desktop/${title}.app/Contents/{Resources,MacOS}
		if [[ $? -ne 0 ]]; then ((e+=1)); fi
		cat ${title}.plist.tmplt | while read line; do
			eval "echo \"${line}\""
		done >~/Desktop/${title}.app/Contents/Info.plist
		if [[ $? -ne 0 ]]; then ((e+=1)); fi
		ln -s ${PWD}/run-${title} ~/Desktop/${title}.app/Contents/MacOS/
		if [[ $? -ne 0 ]]; then ((e+=1)); fi
		cp icons/${title}-*x*.icns ~/Desktop/${title}.app/Contents/Resources/
		if [[ $? -ne 0 ]]; then ((e+=1)); fi
	fi
done
if [[ ${e} -gt 0 ]]; then
	sleep 5
	exit 1
fi
echo "Ready to launch ${PWD}/run-Switchboard and ${PWD}/run-Telephone"
