#!/bin/sh
# $Id: run-Switchboard,v 1.4 2012/02/15 00:36:21 drmiller Exp $

pgm=$(readlink ${0})
pgm=${pgm:-${0}}
export INSTALLPATH=${pgm%/*}
echo "INSTALLPATH=${INSTALLPATH}"
cd ${INSTALLPATH}
exec java -jar switchboard.jar
