#!/bin/sh
# $Id: run-Telephone,v 1.4 2012/02/15 00:36:21 drmiller Exp $

pgm=$(readlink ${0})
pgm=${pgm:-${0}}
export INSTALLPATH=${pgm%/*}
cd ${INSTALLPATH}
# backgrounding allows OSX to run multiple instances
java -jar telephone.jar &
