#!/bin/sh
# $Id: run-Telephone,v 1.3 2012/02/13 14:29:20 drmiller Exp $

export INSTALLPATH=${0%/*}
cd ${INSTALLPATH}
# backgrounding allows OSX to run multiple instances
java -jar telephone.jar "${@}" &
