#!/bin/sh
# $Id: run-Switchboard,v 1.5 2012/02/17 14:52:42 drmiller Exp $

pgm=${0}
if [[ -L ${pgm} ]]; then
	pgm=$(readlink ${pgm})
fi
export SWITCHBOARDHOME=${pgm%/*}
cd ${SWITCHBOARDHOME}
exec java -jar switchboard.jar
