#!/bin/sh
# $Id: run-Telephone,v 1.5 2012/02/17 14:52:42 drmiller Exp $

pgm=${0}
if [[ -L ${pgm} ]]; then
	pgm=$(readlink ${pgm})
fi
export TELEPHONEHOME=${pgm%/*}
cd ${TELEPHONEHOME}
# backgrounding allows OSX to run multiple instances
java -jar telephone.jar &
