#!/bin/sh
# $Id: UNINSTALL,v 1.2 2012/02/19 22:17:02 drmiller Exp $

export INSTALLPATH="${HOME}/tele-sb-sim"

# path might have blanks!!!
cd "${HOME}"
echo "Removing ${INSTALLPATH}..."
rm -rf "${INSTALLPATH}"

for title in Switchboard Telephone; do
	if [[ -f "${HOME}/Desktop/${title}.desktop" ]]; then
		echo "Removing GNOME desktop ${title} shortcut..."
		rm -f "${HOME}/Desktop/${title}.desktop"
	fi
done
